# Generated by Django 3.1.2 on 2020-10-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='postal',
            new_name='postcode',
        ),
    ]
