# Generated by Django 3.1.2 on 2020-10-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20201021_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='days',
            options={},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pricesperday',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registeredchild',
            options={},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={},
        ),
        migrations.AlterField(
            model_name='days',
            name='dow',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='days',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='first_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='nick',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='second_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child', unique=True),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='competition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='children.Days'),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.monitor'),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.paymentmethods'),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='price_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.season', unique=True),
        ),
    ]
