# Generated by Django 3.1.2 on 2020-10-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_auto_20201024_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredchild',
            name='days',
            field=models.ManyToManyField(to='children.Days'),
        ),
    ]
