# Generated by Django 3.1.2 on 2020-10-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_auto_20201024_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='register',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='children.registeredchild'),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='monitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.monitor'),
        ),
        migrations.AlterField(
            model_name='registeredchild',
            name='payment_method',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.paymentmethods'),
        ),
    ]
