# Generated by Django 3.1.2 on 2020-10-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_auto_20201024_1546'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registeredchild',
            unique_together={('child', 'season')},
        ),
    ]
