# Generated by Django 3.1.2 on 2020-10-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_auto_20201024_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesperday',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricesperday',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pricesperday',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.season'),
        ),
    ]
