# Generated by Django 3.1.2 on 2020-10-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0009_auto_20201024_1602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('name', 'first_surname', 'second_surname')},
        ),
    ]
