# Generated by Django 3.1.2 on 2020-11-02 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0013_auto_20201102_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredchild',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.season'),
        ),
    ]
