# Generated by Django 3.1.2 on 2020-11-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0014_auto_20201102_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredchild',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.monitor'),
        ),
    ]
